# frozen_string_literal: true

# this should match bundled ruby version in SketchUp
# check RUBY_VERSION in SketchUp's Developer Console

source 'https://rubygems.org'

gem 'pry'
gem 'rubocop', group: 'development', require: false
